### ISSUE TITLE
Improve Look of GUI

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/tinderpol#18]
The GUI looks currently more functional than modern. If time is left at the end, we should improve the GUI's look as well

**Comment by MalteRichert** [comment]
Idea: change colours in MainActivity to Blue and red from logo? That might make quite a difference with very little effort

**Comment by Rex2002** [comment]
move viewMap button to be an image button

**Comment by Rex2002** [comment]
tinderpol logo red: #df4141
tinderpol logo blue: #298ce3

**Comment by MalteRichert** [comment]
Great job @Rex2002 !🥇 🚀
