### ISSUE TITLE
Error when closing InfoFragment

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/tinderpol#26]
This Error has no apparent effect on the app, but is shown as an error in the logs:
When opening the `NoticeInfoFragment` and then clicking above it (to remove it again), creates the following error to be logged:

```
Window handle Window{aad1256 u0 de.dhbw.tinderpol/de.dhbw.tinderpol.SwipeActivity} has no registered input channel
```

**Comment by MalteRichert** [comment]
Closed due to lack of relevance.
