### ISSUE TITLE
Error when opening / leaving App

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/tinderpol#27]
This error is logged when opening the app or when clicking the button to switch between open apps. In the latter case, the frame shown for our app also appears to look empty (on my machine anyways).

The logged error message is:
```
[Surface(name=AppWindowToken{a83ce8c token=Token{c3ea7bf ActivityRecord{3329de u0 de.dhbw.tinderpol/.SwipeActivity t10}}})/@0xc40e2d9 - animation-leash#0] No local sync point found
```

**Comment by MalteRichert** [comment]
Closed due to lack of relevance.
